export const SAVE_DECK_REQUEST = "SAVE_DECK_REQUEST";
export const GET_DECK_REQUESTS_REQUEST = "GET_DECK_REQUESTS_REQUEST";
export const GET_DECK_REQUEST = "GET_DECK_REQUEST";
export const ADD_QS_DECK_REQUEST = "ADD_QS_DECK_REQUEST";
export const RECEIVE_DECKS_REQUEST = "RECEIVE_DECKS_REQUEST";
